"use client";

import React from "react";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import { ChevronRight, ArrowLeft, FileText, AlertTriangle, ShieldCheck, Scale, CheckCircle2 } from "lucide-react";
import { useThemeAndLang } from "@/lib/themeContext";

export default function TermsPage() {
  const { language } = useThemeAndLang();
  const isHi = language === "hi";

  return (
    <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)] flex flex-col transition-colors duration-200">
      {/* Sticky Header */}
      <Navbar />

      {/* Main Container */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 w-full space-y-8 flex-1">
        {/* Breadcrumb & Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-[var(--border)]">
          <div className="space-y-1.5">
            <nav className="flex items-center gap-2 text-xs font-mono text-[var(--muted-foreground)]">
              <Link href="/" className="hover:text-[#F97316] transition-colors">
                <span>{isHi ? "मैट्रिक्स" : "Matrix"}</span>
              </Link>
              <ChevronRight className="w-3.5 h-3.5" />
              <span className="text-[#F97316] font-semibold">
                {isHi ? "सेवा की शर्तें" : "Terms of Service"}
              </span>
            </nav>

            <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-[var(--foreground)] flex items-center gap-3">
              <span>{isHi ? "सेवा की शर्तें व उपयोगकर्ता अनुबंध" : "Terms of Service & User Agreement"}</span>
              <span className="text-xs font-mono px-2.5 py-0.5 rounded-full bg-[#F97316]/10 border border-[#F97316]/30 text-[#F97316] font-bold">
                Enterprise &bull; v2.0
              </span>
            </h1>

            <p className="text-xs sm:text-sm text-[var(--muted-foreground)] max-w-xl leading-relaxed">
              {isHi
                ? "अंतिम संशोधन: 5 अक्टूबर 2026 • HYPE PORTAL का उपयोग करने पर आप इन कानूनी शर्तों से सहमत होते हैं।"
                : "Last Updated: October 5, 2026 • Governing terms, acceptable AI use policies, and intellectual property conditions."}
            </p>
          </div>

          <Link
            href="/"
            className="inline-flex items-center gap-2 px-3.5 py-2 rounded-xl bg-[var(--card-bg)] border border-[var(--border)] hover:bg-[var(--surface-hover)] text-xs font-mono text-[var(--foreground)] transition cursor-pointer self-start sm:self-auto shrink-0"
          >
            <ArrowLeft className="w-3.5 h-3.5 text-[#F97316]" />
            <span>{isHi ? "वापस होम" : "Back to Matrix"}</span>
          </Link>
        </div>

        {/* 3 Key Takeaways */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="p-4 rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] space-y-2">
            <div className="w-8 h-8 rounded-xl bg-[#F97316]/10 text-[#F97316] flex items-center justify-center">
              <Scale className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-bold text-[var(--foreground)]">
              {isHi ? "उचित उपयोग नीति" : "Fair & Lawful Use"}
            </h3>
            <p className="text-xs text-[var(--muted-foreground)] leading-relaxed">
              {isHi
                ? "सिस्टम का उपयोग किसी भी प्रकार के उत्पीड़न, अवैध डेटा माइनिंग या दुर्भावनापूर्ण उद्देश्यों के लिए प्रतिबंधित है।"
                : "No harassment, automated scraping, malicious payload injection, or unlawful automated generation."}
            </p>
          </div>

          <div className="p-4 rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] space-y-2">
            <div className="w-8 h-8 rounded-xl bg-[#F59E0B]/10 text-[#F59E0B] flex items-center justify-center">
              <AlertTriangle className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-bold text-[var(--foreground)]">
              {isHi ? "एआई डिस्क्लेमर" : "AI Output Disclaimer"}
            </h3>
            <p className="text-xs text-[var(--muted-foreground)] leading-relaxed">
              {isHi
                ? "एआई जनरेटेड रोस्ट्स, राय और उत्तर मनोरंजन व शोध के लिए हैं। वित्तीय या कानूनी सलाह के रूप में न लें।"
                : "Outputs are generated by neural reasoning models for entertainment and advisory purposes. Not certified professional advice."}
            </p>
          </div>

          <div className="p-4 rounded-2xl border border-[var(--border)] bg-[var(--card-bg)] space-y-2">
            <div className="w-8 h-8 rounded-xl bg-purple-500/10 text-purple-500 flex items-center justify-center">
              <ShieldCheck className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-bold text-[var(--foreground)]">
              {isHi ? "18+ परिपक्व मोड" : "18+ Mature Personalities"}
            </h3>
            <p className="text-xs text-[var(--muted-foreground)] leading-relaxed">
              {isHi
                ? "नॉटी व सेवेज रोस्ट मोड में अनफ़िल्टर्ड व्यंग्य शामिल है, जो केवल 18 वर्ष या उससे अधिक आयु के उपयोगकर्ताओं के लिए है।"
                : "Noty & Savage modes contain mature satire and spicy banter intended exclusively for audiences 18 years of age or older."}
            </p>
          </div>
        </div>

        {/* Full Terms Articles */}
        <div className="space-y-6 text-xs sm:text-sm text-[var(--foreground)] leading-relaxed glass rounded-2xl p-6 sm:p-8 border border-[var(--border)] bg-[var(--card-bg)]">
          <section className="space-y-2">
            <h2 className="text-base sm:text-lg font-bold text-[var(--foreground)] tracking-tight">
              1. Acceptance of Terms
            </h2>
            <p className="text-[var(--muted-foreground)]">
              By accessing, browsing, or using HYPE PORTAL (&ldquo;the Platform&rdquo;), operated by PR Creations Lab, you agree to be bound by these Terms of Service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base sm:text-lg font-bold text-[var(--foreground)] tracking-tight">
              2. Permitted and Prohibited Conduct
            </h2>
            <p className="text-[var(--muted-foreground)]">
              Users are strictly prohibited from utilizing the platform or its serverless endpoints to:
            </p>
            <ul className="list-disc list-inside space-y-1 text-[var(--muted-foreground)] pl-2">
              <li>Transmit hate speech, defamatory harassment, or non-consensual deepfakes.</li>
              <li>Attempt to reverse-engineer system prompts, bypass safety filters, or conduct denial-of-service stress tests.</li>
              <li>Automate excessive unauthenticated queries that degrade platform availability for other users.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-base sm:text-lg font-bold text-[var(--foreground)] tracking-tight">
              3. Intellectual Property Rights
            </h2>
            <p className="text-[var(--muted-foreground)]">
              You retain all ownership rights in the original inputs, text, and prompts you provide to the platform. HYPE PORTAL retains full intellectual property rights, trademarks, visual design tokens, and algorithmic logic underlying the Intelligence Matrix.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base sm:text-lg font-bold text-[var(--foreground)] tracking-tight">
              4. Disclaimer of Warranties
            </h2>
            <p className="text-[var(--muted-foreground)]">
              The services and AI outputs are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties of any kind, whether express or implied. HYPE PORTAL makes no guarantee regarding the factual accuracy of AI roasts, sentiment evaluations, or community debate outcomes.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base sm:text-lg font-bold text-[var(--foreground)] tracking-tight">
              5. Governing Law and Dispute Resolution
            </h2>
            <p className="text-[var(--muted-foreground)]">
              These terms are governed by and construed in accordance with the laws of India. Any disputes arising in connection with the Platform shall be resolved under the jurisdiction of the competent courts of India.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base sm:text-lg font-bold text-[var(--foreground)] tracking-tight">
              6. Contact Information
            </h2>
            <p className="text-[var(--muted-foreground)]">
              For any questions or legal inquiries regarding these Terms of Service, please reach out to us via{" "}
              <Link
                href="/contact"
                className="text-[#F97316] underline font-medium hover:text-[#EA580C] transition"
              >
                Official Contact Desk
              </Link>{" "}
              or{" "}
              <a
                href="mailto:ask.hypeai@gmail.com"
                className="text-[#F97316] underline font-medium hover:text-[#EA580C] transition"
                title="Direct Email"
              >
                Contact via Email
              </a>.
            </p>
          </section>
        </div>
      </main>

      {/* Subfooter */}
      <footer className="border-t border-[#1E293B] bg-[#0B1220] text-[#CBD5E1] py-8 text-xs font-mono text-center">
        <div className="max-w-4xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            &copy; 2026{" "}
            <a
              href="https://instagram.com/iprcreations"
              target="_blank"
              rel="noopener noreferrer"
              className="text-white hover:text-[#F97316] transition underline decoration-dotted underline-offset-4 font-semibold"
            >
              PR Creations Lab.
            </a>{" "}
            &bull; Terms of Service
          </div>
          <div className="flex items-center gap-4">
            <Link href="/contact" className="hover:text-[#F97316] transition">
              Contact
            </Link>
            <Link href="/docs" className="hover:text-[#F97316] transition">
              Documentation
            </Link>
            <Link href="/privacy" className="hover:text-[#F97316] transition">
              Privacy Policy
            </Link>
            <Link href="/security" className="hover:text-[#F97316] transition">
              Security
            </Link>
            <Link href="/sitemap" className="hover:text-[#F97316] transition">
              Sitemap
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
